#!/usr/bin/env python3
"""Print an annotated YAML field reference for a polycv CV.

Reads the JSON Schema (built from schema.cue) so every field, its type and
its description stay in sync. This is a *reference* of available fields and
types — not filled-in sample data. For a realistic example, see cv.yml.

Usage: gen-reference.py [schema.json | https://…/schema.json]
Defaults to a schema.json next to this script.
"""
import json
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "schema.json")
if src.startswith("http"):
    DEFS = json.loads(urllib.request.urlopen(src).read())["$defs"]
else:
    DEFS = json.load(open(src))["$defs"]

# Preferred field order per def (schema.cue order); unknown fields appended.
ORDER = {
    "CvMeta": [
        "photo", "locale", "header-band", "header-band-summary",
        "header-band-contact", "ats-split", "entry-inline-meta",
        "keywords-lines", "sidebar-sections", "main-sections",
        "section-titles", "section-icons",
    ],
    "CV": [
        "name", "headline", "location", "keywords", "email", "phone",
        "address", "summary", "motivation", "values", "hobbies",
        "references", "profiles", "skills", "experience", "education",
        "awards", "involvement", "courses", "publications",
    ],
    "Entry": [
        "name", "company", "position", "summary", "location",
        "start_date", "end_date", "date", "highlights",
    ],
    "SkillEntry": ["group", "items"],
    "SocialNetwork": ["network", "username"],
    "PublicationEntry": [
        "title", "authors", "summary", "doi", "url", "journal", "date",
    ],
}
# Defs expanded inline as a single sample list item.
ENTRY_LIKE = {"Entry", "PublicationEntry", "SkillEntry", "SocialNetwork"}
COMMENT_COL = 46


# Short utility types are inlined; SectionName is shown by name (see legend).
UTIL_INLINE = {"Date", "ExactDate"}


def typestr(node):
    if "$ref" in node:
        name = node["$ref"].split("/")[-1]
        return typestr(DEFS[name]) if name in UTIL_INLINE else name
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    if "const" in node:
        return json.dumps(node["const"])
    if "anyOf" in node:
        return " | ".join(typestr(x) for x in node["anyOf"])
    if "allOf" in node:  # cue emits `int & >=0` as an allOf; merge the members
        merged = {}
        for m in node["allOf"]:
            merged.update(m)
        return typestr(merged)
    t = node.get("type")
    if t == "array":
        return "[" + typestr(node.get("items", {})) + "]"
    if t == "object":
        ap = node.get("additionalProperties")
        if isinstance(ap, dict):
            return "{key: " + typestr(ap) + "}"
        return "object"
    if t == "integer":
        return "integer" + (" >= %s" % node["minimum"] if "minimum" in node else "")
    return {"boolean": "bool", "string": "string"}.get(t, t or "any")


def array_ref(node):
    if node.get("type") == "array" and "$ref" in node.get("items", {}):
        return node["items"]["$ref"].split("/")[-1]
    return None


def ordered(defname, props):
    order = ORDER.get(defname, [])
    return [k for k in order if k in props] + sorted(
        k for k in props if k not in order
    )


def fmt(indent, code, desc):
    line = " " * indent + code
    if desc:
        line = (line + " " if len(line) < COMMENT_COL else line + "  ")
        line = line.ljust(COMMENT_COL) + "# " + desc
    return line.rstrip()


def describe(node, key, required):
    desc = " ".join(node.get("description", "").split())  # collapse newlines
    return ("required — " + desc if key in required else desc)


def emit(defname, indent):
    node = DEFS[defname]
    props = node["properties"]
    required = set(node.get("required", []))
    out = []
    for k in ordered(defname, props):
        p = props[k]
        ref = array_ref(p)
        if ref in ENTRY_LIKE:
            out.append(fmt(indent, "%s:" % k, describe(p, k, required)))
            item = emit(ref, indent + 4)
            item[0] = " " * (indent + 2) + "- " + item[0].lstrip()
            out += item
        else:
            out.append(fmt(indent, "%s: <%s>" % (k, typestr(p)), describe(p, k, required)))
    return out


print("# polycv CV field reference — generated by `make yaml-reference`.")
print("# <type> shows the value type. Fields are optional unless the comment")
print("# says 'required'. For a filled example, see cv.yml.")
print()
print(fmt(0, "meta:", DEFS["CvMeta"].get("description", "Layout / configuration.")))
print("\n".join(emit("CvMeta", 2)))
print()
print(fmt(0, "cv:", "CV data."))
print("\n".join(emit("CV", 2)))
print()
print("# SectionName (values for sidebar-sections / main-sections / section-*):")
print("#   " + " | ".join(DEFS["SectionName"]["enum"]))
